# Generated by Django 5.1 on 2024-08-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_is_admin_usuario_is_approved_usuario_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
    ]
