# Generated by Django 5.1 on 2024-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_is_admin_remove_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.CharField(default='abc', max_length=255),
        ),
    ]
