# Generated by Django 5.1 on 2024-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
