# Generated by Django 5.1 on 2024-09-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
