# Generated by Django 5.1 on 2024-08-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
