# Generated by Django 5.1 on 2024-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='criado_por',
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
