# Generated by Django 5.1 on 2024-08-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_produto_criado_por_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
