# Generated by Django 5.1 on 2024-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='TEMP_CODE', editable=False, max_length=4, unique=True),
        ),
    ]
