# Generated by Django 5.1 on 2024-09-10 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
